plugins {
  id 'org.owasp.dependencycheck' version '12.1.8'
  id 'scala'
  id 'java-library'
  id 'io.gatling.gradle' version '3.9.5'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

tasks.withType(JavaExec) {
  /* Configure the size of the JVM if necessary
  jvmArgs = ['-Xms1024m', '-Xmx2048m']
  */
  /* Use the following args to build a report when a test was terminated
  args = [
      "--reports-only", "<gatling-run-id>",
      '--results-folder', file('build/reports/gatling').absolutePath,
      ]
  */
}

tasks.withType(Copy).all{
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

repositories {
  mavenCentral()
}

gatling {
  gatlingVersion '3.9.5'
  scalaVersion '2.13.10'
  simulations = {
    include "simulations/XUI_DataPrep.scala"
  }
}

sourceSets {
  gatling {
    scala {
      srcDir 'src/gatling/simulations'
    }
    resources {
      srcDir 'src/gatling/resources'
    }
  }
}